directories:
  output: release
  buildResources: build
appId: com.dukabook.app
productName: DukaBook
copyright: Copyright Â© 2024 DukaBook
files:
  - filter:
      - dist/**/*
      - electron.js
      - public/**/*
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
    - target: portable
      arch:
        - x64
  icon: public/logo.png
  artifactName: DukaBook-${version}-${platform}-${arch}.${ext}
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: public/logo.png
  uninstallerIcon: public/logo.png
  installerHeaderIcon: public/logo.png
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: DukaBook
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
    - target: zip
      arch:
        - x64
        - arm64
  icon: public/logo.png
  category: public.app-category.business
  artifactName: DukaBook-${version}-${platform}-${arch}.${ext}
dmg:
  title: DukaBook Installer
  icon: public/logo.png
linux:
  target:
    - target: AppImage
      arch:
        - x64
    - target: deb
      arch:
        - x64
    - target: rpm
      arch:
        - x64
  icon: public/logo.png
  category: Office
  artifactName: DukaBook-${version}-${platform}-${arch}.${ext}
electronVersion: 39.2.6
